package com.ssm.dao.shiro;

import com.ssm.model.shiro.CommGroup;
import java.util.List;

public interface CommGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group
     *
     * @mbggenerated
     */
    int insert(CommGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group
     *
     * @mbggenerated
     */
    CommGroup selectByPrimaryKey(Long groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group
     *
     * @mbggenerated
     */
    List<CommGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommGroup record);
}