package com.ssm.dao.shiro;

import com.ssm.model.shiro.GroupUser;
import java.util.List;

public interface GroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long groupUsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_user
     *
     * @mbggenerated
     */
    int insert(GroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_user
     *
     * @mbggenerated
     */
    GroupUser selectByPrimaryKey(Long groupUsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_user
     *
     * @mbggenerated
     */
    List<GroupUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupUser record);
}