package com.ssm.dao.shiro;

import com.ssm.model.shiro.GroupSrc;
import java.util.List;

public interface GroupSrcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_src
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_src
     *
     * @mbggenerated
     */
    int insert(GroupSrc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_src
     *
     * @mbggenerated
     */
    GroupSrc selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_src
     *
     * @mbggenerated
     */
    List<GroupSrc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_src
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GroupSrc record);
}