package com.ssm.dao.shiro;

import com.ssm.model.shiro.Src;
import java.util.List;

public interface SrcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer srcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src
     *
     * @mbggenerated
     */
    int insert(Src record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src
     *
     * @mbggenerated
     */
    Src selectByPrimaryKey(Integer srcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src
     *
     * @mbggenerated
     */
    List<Src> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Src record);
}