package com.ssm.dao;

import com.ssm.model.Album;
import java.util.List;

public interface AlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int insert(Album record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    Album selectByPrimaryKey(Long albumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    List<Album> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Album record);
}