package com.ssm.dao;

import com.ssm.model.AlbumPicture;
import java.util.List;

public interface AlbumPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long albPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    int insert(AlbumPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    AlbumPicture selectByPrimaryKey(Long albPicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    List<AlbumPicture> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AlbumPicture record);
}