package com.ssm.dao;

import com.ssm.model.Picture;
import java.util.List;

public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated
     */
    Picture selectByPrimaryKey(Long picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated
     */
    List<Picture> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Picture record);
}