package com.ssm.dao;

import com.ssm.model.UserAlbum;
import java.util.List;

public interface UserAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userAlbumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int insert(UserAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    UserAlbum selectByPrimaryKey(Long userAlbumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    List<UserAlbum> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAlbum record);
}