package com.ssm.dao.shiro.baseshiro;

import com.ssm.model.shiro.CommGroupRole;
import java.util.List;

public interface CommGroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long groupRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    int insert(CommGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    CommGroupRole selectByPrimaryKey(Long groupRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    List<CommGroupRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommGroupRole record);
}