package com.ssm.dao.shiro.baseshiro;

import com.ssm.model.shiro.CommGroupUser;
import java.util.List;

public interface CommGroupUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long groupUsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_user
     *
     * @mbggenerated
     */
    int insert(CommGroupUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_user
     *
     * @mbggenerated
     */
    CommGroupUser selectByPrimaryKey(Long groupUsrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_user
     *
     * @mbggenerated
     */
    List<CommGroupUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommGroupUser record);
}