package com.ssm.dao.shiro.baseshiro;

import com.ssm.model.shiro.RoleSimplePermission;
import java.util.List;

public interface RoleSimplePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long roleSimplePerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    int insert(RoleSimplePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    RoleSimplePermission selectByPrimaryKey(Long roleSimplePerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    List<RoleSimplePermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleSimplePermission record);
}