package com.ssm.dao.shiro.baseshiro;

import com.ssm.model.shiro.SimplePermission;
import java.util.List;

public interface SimplePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_permission
     *
     * @mbggenerated
     */
    int insert(SimplePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_permission
     *
     * @mbggenerated
     */
    SimplePermission selectByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_permission
     *
     * @mbggenerated
     */
    List<SimplePermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SimplePermission record);
}