package com.ssm.model.shiro;

import java.io.Serializable;

public class CommGroupRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_group_role.group_role_id
     *
     * @mbggenerated
     */
    private Long groupRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_group_role.group_id
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_group_role.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_group_role.group_role_id
     *
     * @return the value of comm_group_role.group_role_id
     *
     * @mbggenerated
     */
    public Long getGroupRoleId() {
        return groupRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_group_role.group_role_id
     *
     * @param groupRoleId the value for comm_group_role.group_role_id
     *
     * @mbggenerated
     */
    public void setGroupRoleId(Long groupRoleId) {
        this.groupRoleId = groupRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_group_role.group_id
     *
     * @return the value of comm_group_role.group_id
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_group_role.group_id
     *
     * @param groupId the value for comm_group_role.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_group_role.role_id
     *
     * @return the value of comm_group_role.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_group_role.role_id
     *
     * @param roleId the value for comm_group_role.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CommGroupRole other = (CommGroupRole) that;
        return (this.getGroupRoleId() == null ? other.getGroupRoleId() == null : this.getGroupRoleId().equals(other.getGroupRoleId()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupRoleId() == null) ? 0 : getGroupRoleId().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_group_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", groupRoleId=").append(groupRoleId);
        sb.append(", groupId=").append(groupId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}