package com.ssm.model.shiro;

import java.io.Serializable;

public class GroupSrc implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_src.rid
     *
     * @mbggenerated
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_src.groupid
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_src.srcid
     *
     * @mbggenerated
     */
    private Integer srcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_src.shiro
     *
     * @mbggenerated
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table group_src
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_src.rid
     *
     * @return the value of group_src.rid
     *
     * @mbggenerated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_src.rid
     *
     * @param rid the value for group_src.rid
     *
     * @mbggenerated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_src.groupid
     *
     * @return the value of group_src.groupid
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_src.groupid
     *
     * @param groupid the value for group_src.groupid
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_src.srcid
     *
     * @return the value of group_src.srcid
     *
     * @mbggenerated
     */
    public Integer getSrcid() {
        return srcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_src.srcid
     *
     * @param srcid the value for group_src.srcid
     *
     * @mbggenerated
     */
    public void setSrcid(Integer srcid) {
        this.srcid = srcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_src.shiro
     *
     * @return the value of group_src.shiro
     *
     * @mbggenerated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_src.shiro
     *
     * @param permission the value for group_src.shiro
     *
     * @mbggenerated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_src
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GroupSrc other = (GroupSrc) that;
        return (this.getRid() == null ? other.getRid() == null : this.getRid().equals(other.getRid()))
            && (this.getGroupid() == null ? other.getGroupid() == null : this.getGroupid().equals(other.getGroupid()))
            && (this.getSrcid() == null ? other.getSrcid() == null : this.getSrcid().equals(other.getSrcid()))
            && (this.getPermission() == null ? other.getPermission() == null : this.getPermission().equals(other.getPermission()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_src
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRid() == null) ? 0 : getRid().hashCode());
        result = prime * result + ((getGroupid() == null) ? 0 : getGroupid().hashCode());
        result = prime * result + ((getSrcid() == null) ? 0 : getSrcid().hashCode());
        result = prime * result + ((getPermission() == null) ? 0 : getPermission().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_src
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", groupid=").append(groupid);
        sb.append(", srcid=").append(srcid);
        sb.append(", shiro=").append(permission);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}