package com.ssm.model.shiro;

import java.io.Serializable;

public class Permission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro.perid
     *
     * @mbggenerated
     */
    private Integer perid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiro.shiro
     *
     * @mbggenerated
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shiro
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro.perid
     *
     * @return the value of shiro.perid
     *
     * @mbggenerated
     */
    public Integer getPerid() {
        return perid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro.perid
     *
     * @param perid the value for shiro.perid
     *
     * @mbggenerated
     */
    public void setPerid(Integer perid) {
        this.perid = perid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shiro.shiro
     *
     * @return the value of shiro.shiro
     *
     * @mbggenerated
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shiro.shiro
     *
     * @param permission the value for shiro.shiro
     *
     * @mbggenerated
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Permission other = (Permission) that;
        return (this.getPerid() == null ? other.getPerid() == null : this.getPerid().equals(other.getPerid()))
            && (this.getPermission() == null ? other.getPermission() == null : this.getPermission().equals(other.getPermission()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPerid() == null) ? 0 : getPerid().hashCode());
        result = prime * result + ((getPermission() == null) ? 0 : getPermission().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiro
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", perid=").append(perid);
        sb.append(", shiro=").append(permission);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}