package com.ssm.model.shiro;

import java.io.Serializable;

public class RoleSimplePermission implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_simple_permission.role_simple_per_id
     *
     * @mbggenerated
     */
    private Long roleSimplePerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_simple_permission.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_simple_permission.permission_id
     *
     * @mbggenerated
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_simple_permission.role_simple_per_id
     *
     * @return the value of role_simple_permission.role_simple_per_id
     *
     * @mbggenerated
     */
    public Long getRoleSimplePerId() {
        return roleSimplePerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_simple_permission.role_simple_per_id
     *
     * @param roleSimplePerId the value for role_simple_permission.role_simple_per_id
     *
     * @mbggenerated
     */
    public void setRoleSimplePerId(Long roleSimplePerId) {
        this.roleSimplePerId = roleSimplePerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_simple_permission.role_id
     *
     * @return the value of role_simple_permission.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_simple_permission.role_id
     *
     * @param roleId the value for role_simple_permission.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_simple_permission.permission_id
     *
     * @return the value of role_simple_permission.permission_id
     *
     * @mbggenerated
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_simple_permission.permission_id
     *
     * @param permissionId the value for role_simple_permission.permission_id
     *
     * @mbggenerated
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleSimplePermission other = (RoleSimplePermission) that;
        return (this.getRoleSimplePerId() == null ? other.getRoleSimplePerId() == null : this.getRoleSimplePerId().equals(other.getRoleSimplePerId()))
            && (this.getRoleId() == null ? other.getRoleId() == null : this.getRoleId().equals(other.getRoleId()))
            && (this.getPermissionId() == null ? other.getPermissionId() == null : this.getPermissionId().equals(other.getPermissionId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoleSimplePerId() == null) ? 0 : getRoleSimplePerId().hashCode());
        result = prime * result + ((getRoleId() == null) ? 0 : getRoleId().hashCode());
        result = prime * result + ((getPermissionId() == null) ? 0 : getPermissionId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_simple_permission
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleSimplePerId=").append(roleSimplePerId);
        sb.append(", roleId=").append(roleId);
        sb.append(", permissionId=").append(permissionId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}