package com.ssm.model.shiro;

import java.io.Serializable;

public class Src implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src.srcid
     *
     * @mbggenerated
     */
    private Integer srcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column src.src_name
     *
     * @mbggenerated
     */
    private String srcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table src
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src.srcid
     *
     * @return the value of src.srcid
     *
     * @mbggenerated
     */
    public Integer getSrcid() {
        return srcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src.srcid
     *
     * @param srcid the value for src.srcid
     *
     * @mbggenerated
     */
    public void setSrcid(Integer srcid) {
        this.srcid = srcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column src.src_name
     *
     * @return the value of src.src_name
     *
     * @mbggenerated
     */
    public String getSrcName() {
        return srcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column src.src_name
     *
     * @param srcName the value for src.src_name
     *
     * @mbggenerated
     */
    public void setSrcName(String srcName) {
        this.srcName = srcName == null ? null : srcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Src other = (Src) that;
        return (this.getSrcid() == null ? other.getSrcid() == null : this.getSrcid().equals(other.getSrcid()))
            && (this.getSrcName() == null ? other.getSrcName() == null : this.getSrcName().equals(other.getSrcName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSrcid() == null) ? 0 : getSrcid().hashCode());
        result = prime * result + ((getSrcName() == null) ? 0 : getSrcName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table src
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", srcid=").append(srcid);
        sb.append(", srcName=").append(srcName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}