package com.ssm.model;

import java.io.Serializable;

public class AlbumPicture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_picture.alb_pic_id
     *
     * @mbggenerated
     */
    private Long albPicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_picture.album_id
     *
     * @mbggenerated
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_picture.picture_id
     *
     * @mbggenerated
     */
    private Long pictureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_picture.alb_pic_id
     *
     * @return the value of album_picture.alb_pic_id
     *
     * @mbggenerated
     */
    public Long getAlbPicId() {
        return albPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_picture.alb_pic_id
     *
     * @param albPicId the value for album_picture.alb_pic_id
     *
     * @mbggenerated
     */
    public void setAlbPicId(Long albPicId) {
        this.albPicId = albPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_picture.album_id
     *
     * @return the value of album_picture.album_id
     *
     * @mbggenerated
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_picture.album_id
     *
     * @param albumId the value for album_picture.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_picture.picture_id
     *
     * @return the value of album_picture.picture_id
     *
     * @mbggenerated
     */
    public Long getPictureId() {
        return pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_picture.picture_id
     *
     * @param pictureId the value for album_picture.picture_id
     *
     * @mbggenerated
     */
    public void setPictureId(Long pictureId) {
        this.pictureId = pictureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AlbumPicture other = (AlbumPicture) that;
        return (this.getAlbPicId() == null ? other.getAlbPicId() == null : this.getAlbPicId().equals(other.getAlbPicId()))
            && (this.getAlbumId() == null ? other.getAlbumId() == null : this.getAlbumId().equals(other.getAlbumId()))
            && (this.getPictureId() == null ? other.getPictureId() == null : this.getPictureId().equals(other.getPictureId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAlbPicId() == null) ? 0 : getAlbPicId().hashCode());
        result = prime * result + ((getAlbumId() == null) ? 0 : getAlbumId().hashCode());
        result = prime * result + ((getPictureId() == null) ? 0 : getPictureId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", albPicId=").append(albPicId);
        sb.append(", albumId=").append(albumId);
        sb.append(", pictureId=").append(pictureId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}