package com.ssm.model;

import java.io.Serializable;

public class Album implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.album_id
     *
     * @mbggenerated
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.author_id
     *
     * @mbggenerated
     */
    private Long authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.create_at
     *
     * @mbggenerated
     */
    private Long createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.album_title
     *
     * @mbggenerated
     */
    private String albumTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album.album_desc
     *
     * @mbggenerated
     */
    private String albumDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table album
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.album_id
     *
     * @return the value of album.album_id
     *
     * @mbggenerated
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.album_id
     *
     * @param albumId the value for album.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.author_id
     *
     * @return the value of album.author_id
     *
     * @mbggenerated
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.author_id
     *
     * @param authorId the value for album.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.create_at
     *
     * @return the value of album.create_at
     *
     * @mbggenerated
     */
    public Long getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.create_at
     *
     * @param createAt the value for album.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Long createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.album_title
     *
     * @return the value of album.album_title
     *
     * @mbggenerated
     */
    public String getAlbumTitle() {
        return albumTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.album_title
     *
     * @param albumTitle the value for album.album_title
     *
     * @mbggenerated
     */
    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle == null ? null : albumTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album.album_desc
     *
     * @return the value of album.album_desc
     *
     * @mbggenerated
     */
    public String getAlbumDesc() {
        return albumDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album.album_desc
     *
     * @param albumDesc the value for album.album_desc
     *
     * @mbggenerated
     */
    public void setAlbumDesc(String albumDesc) {
        this.albumDesc = albumDesc == null ? null : albumDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Album other = (Album) that;
        return (this.getAlbumId() == null ? other.getAlbumId() == null : this.getAlbumId().equals(other.getAlbumId()))
            && (this.getAuthorId() == null ? other.getAuthorId() == null : this.getAuthorId().equals(other.getAuthorId()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()))
            && (this.getAlbumTitle() == null ? other.getAlbumTitle() == null : this.getAlbumTitle().equals(other.getAlbumTitle()))
            && (this.getAlbumDesc() == null ? other.getAlbumDesc() == null : this.getAlbumDesc().equals(other.getAlbumDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAlbumId() == null) ? 0 : getAlbumId().hashCode());
        result = prime * result + ((getAuthorId() == null) ? 0 : getAuthorId().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result + ((getAlbumTitle() == null) ? 0 : getAlbumTitle().hashCode());
        result = prime * result + ((getAlbumDesc() == null) ? 0 : getAlbumDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", albumId=").append(albumId);
        sb.append(", authorId=").append(authorId);
        sb.append(", createAt=").append(createAt);
        sb.append(", albumTitle=").append(albumTitle);
        sb.append(", albumDesc=").append(albumDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}