package com.ssm.model;

import java.io.Serializable;

public class AlbumPicture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_picture.al_pic_id
     *
     * @mbggenerated
     */
    private Long alPicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_picture.album_id
     *
     * @mbggenerated
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column album_picture.pic_id
     *
     * @mbggenerated
     */
    private Long picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_picture.al_pic_id
     *
     * @return the value of album_picture.al_pic_id
     *
     * @mbggenerated
     */
    public Long getAlPicId() {
        return alPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_picture.al_pic_id
     *
     * @param alPicId the value for album_picture.al_pic_id
     *
     * @mbggenerated
     */
    public void setAlPicId(Long alPicId) {
        this.alPicId = alPicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_picture.album_id
     *
     * @return the value of album_picture.album_id
     *
     * @mbggenerated
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_picture.album_id
     *
     * @param albumId the value for album_picture.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column album_picture.pic_id
     *
     * @return the value of album_picture.pic_id
     *
     * @mbggenerated
     */
    public Long getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column album_picture.pic_id
     *
     * @param picId the value for album_picture.pic_id
     *
     * @mbggenerated
     */
    public void setPicId(Long picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AlbumPicture other = (AlbumPicture) that;
        return (this.getAlPicId() == null ? other.getAlPicId() == null : this.getAlPicId().equals(other.getAlPicId()))
            && (this.getAlbumId() == null ? other.getAlbumId() == null : this.getAlbumId().equals(other.getAlbumId()))
            && (this.getPicId() == null ? other.getPicId() == null : this.getPicId().equals(other.getPicId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAlPicId() == null) ? 0 : getAlPicId().hashCode());
        result = prime * result + ((getAlbumId() == null) ? 0 : getAlbumId().hashCode());
        result = prime * result + ((getPicId() == null) ? 0 : getPicId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album_picture
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", alPicId=").append(alPicId);
        sb.append(", albumId=").append(albumId);
        sb.append(", picId=").append(picId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}