package com.ssm.model;

import java.io.Serializable;

public class Comment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comm_pid
     *
     * @mbggenerated
     */
    private Integer commPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comm_authorid
     *
     * @mbggenerated
     */
    private Integer commAuthorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comm_create_at
     *
     * @mbggenerated
     */
    private Integer commCreateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comm_content
     *
     * @mbggenerated
     */
    private String commContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.cid
     *
     * @return the value of comment.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.cid
     *
     * @param cid the value for comment.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comm_pid
     *
     * @return the value of comment.comm_pid
     *
     * @mbggenerated
     */
    public Integer getCommPid() {
        return commPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comm_pid
     *
     * @param commPid the value for comment.comm_pid
     *
     * @mbggenerated
     */
    public void setCommPid(Integer commPid) {
        this.commPid = commPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comm_authorid
     *
     * @return the value of comment.comm_authorid
     *
     * @mbggenerated
     */
    public Integer getCommAuthorid() {
        return commAuthorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comm_authorid
     *
     * @param commAuthorid the value for comment.comm_authorid
     *
     * @mbggenerated
     */
    public void setCommAuthorid(Integer commAuthorid) {
        this.commAuthorid = commAuthorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comm_create_at
     *
     * @return the value of comment.comm_create_at
     *
     * @mbggenerated
     */
    public Integer getCommCreateAt() {
        return commCreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comm_create_at
     *
     * @param commCreateAt the value for comment.comm_create_at
     *
     * @mbggenerated
     */
    public void setCommCreateAt(Integer commCreateAt) {
        this.commCreateAt = commCreateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comm_content
     *
     * @return the value of comment.comm_content
     *
     * @mbggenerated
     */
    public String getCommContent() {
        return commContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comm_content
     *
     * @param commContent the value for comment.comm_content
     *
     * @mbggenerated
     */
    public void setCommContent(String commContent) {
        this.commContent = commContent == null ? null : commContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Comment other = (Comment) that;
        return (this.getCid() == null ? other.getCid() == null : this.getCid().equals(other.getCid()))
            && (this.getCommPid() == null ? other.getCommPid() == null : this.getCommPid().equals(other.getCommPid()))
            && (this.getCommAuthorid() == null ? other.getCommAuthorid() == null : this.getCommAuthorid().equals(other.getCommAuthorid()))
            && (this.getCommCreateAt() == null ? other.getCommCreateAt() == null : this.getCommCreateAt().equals(other.getCommCreateAt()))
            && (this.getCommContent() == null ? other.getCommContent() == null : this.getCommContent().equals(other.getCommContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCid() == null) ? 0 : getCid().hashCode());
        result = prime * result + ((getCommPid() == null) ? 0 : getCommPid().hashCode());
        result = prime * result + ((getCommAuthorid() == null) ? 0 : getCommAuthorid().hashCode());
        result = prime * result + ((getCommCreateAt() == null) ? 0 : getCommCreateAt().hashCode());
        result = prime * result + ((getCommContent() == null) ? 0 : getCommContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cid=").append(cid);
        sb.append(", commPid=").append(commPid);
        sb.append(", commAuthorid=").append(commAuthorid);
        sb.append(", commCreateAt=").append(commCreateAt);
        sb.append(", commContent=").append(commContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}