package com.ssm.model;

import java.io.Serializable;

public class Picture implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_id
     *
     * @mbggenerated
     */
    private Long picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_title
     *
     * @mbggenerated
     */
    private String picTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.uploader_id
     *
     * @mbggenerated
     */
    private Long uploaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.upload_at
     *
     * @mbggenerated
     */
    private Long uploadAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.thumb_num
     *
     * @mbggenerated
     */
    private Long thumbNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.collected_num
     *
     * @mbggenerated
     */
    private Long collectedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pic_desc
     *
     * @mbggenerated
     */
    private String picDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table picture
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_id
     *
     * @return the value of picture.pic_id
     *
     * @mbggenerated
     */
    public Long getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_id
     *
     * @param picId the value for picture.pic_id
     *
     * @mbggenerated
     */
    public void setPicId(Long picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_title
     *
     * @return the value of picture.pic_title
     *
     * @mbggenerated
     */
    public String getPicTitle() {
        return picTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_title
     *
     * @param picTitle the value for picture.pic_title
     *
     * @mbggenerated
     */
    public void setPicTitle(String picTitle) {
        this.picTitle = picTitle == null ? null : picTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.uploader_id
     *
     * @return the value of picture.uploader_id
     *
     * @mbggenerated
     */
    public Long getUploaderId() {
        return uploaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.uploader_id
     *
     * @param uploaderId the value for picture.uploader_id
     *
     * @mbggenerated
     */
    public void setUploaderId(Long uploaderId) {
        this.uploaderId = uploaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.upload_at
     *
     * @return the value of picture.upload_at
     *
     * @mbggenerated
     */
    public Long getUploadAt() {
        return uploadAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.upload_at
     *
     * @param uploadAt the value for picture.upload_at
     *
     * @mbggenerated
     */
    public void setUploadAt(Long uploadAt) {
        this.uploadAt = uploadAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.path
     *
     * @return the value of picture.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.path
     *
     * @param path the value for picture.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.url
     *
     * @return the value of picture.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.url
     *
     * @param url the value for picture.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.thumb_num
     *
     * @return the value of picture.thumb_num
     *
     * @mbggenerated
     */
    public Long getThumbNum() {
        return thumbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.thumb_num
     *
     * @param thumbNum the value for picture.thumb_num
     *
     * @mbggenerated
     */
    public void setThumbNum(Long thumbNum) {
        this.thumbNum = thumbNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.collected_num
     *
     * @return the value of picture.collected_num
     *
     * @mbggenerated
     */
    public Long getCollectedNum() {
        return collectedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.collected_num
     *
     * @param collectedNum the value for picture.collected_num
     *
     * @mbggenerated
     */
    public void setCollectedNum(Long collectedNum) {
        this.collectedNum = collectedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pic_desc
     *
     * @return the value of picture.pic_desc
     *
     * @mbggenerated
     */
    public String getPicDesc() {
        return picDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pic_desc
     *
     * @param picDesc the value for picture.pic_desc
     *
     * @mbggenerated
     */
    public void setPicDesc(String picDesc) {
        this.picDesc = picDesc == null ? null : picDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Picture other = (Picture) that;
        return (this.getPicId() == null ? other.getPicId() == null : this.getPicId().equals(other.getPicId()))
            && (this.getPicTitle() == null ? other.getPicTitle() == null : this.getPicTitle().equals(other.getPicTitle()))
            && (this.getUploaderId() == null ? other.getUploaderId() == null : this.getUploaderId().equals(other.getUploaderId()))
            && (this.getUploadAt() == null ? other.getUploadAt() == null : this.getUploadAt().equals(other.getUploadAt()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getThumbNum() == null ? other.getThumbNum() == null : this.getThumbNum().equals(other.getThumbNum()))
            && (this.getCollectedNum() == null ? other.getCollectedNum() == null : this.getCollectedNum().equals(other.getCollectedNum()))
            && (this.getPicDesc() == null ? other.getPicDesc() == null : this.getPicDesc().equals(other.getPicDesc()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPicId() == null) ? 0 : getPicId().hashCode());
        result = prime * result + ((getPicTitle() == null) ? 0 : getPicTitle().hashCode());
        result = prime * result + ((getUploaderId() == null) ? 0 : getUploaderId().hashCode());
        result = prime * result + ((getUploadAt() == null) ? 0 : getUploadAt().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getThumbNum() == null) ? 0 : getThumbNum().hashCode());
        result = prime * result + ((getCollectedNum() == null) ? 0 : getCollectedNum().hashCode());
        result = prime * result + ((getPicDesc() == null) ? 0 : getPicDesc().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", picId=").append(picId);
        sb.append(", picTitle=").append(picTitle);
        sb.append(", uploaderId=").append(uploaderId);
        sb.append(", uploadAt=").append(uploadAt);
        sb.append(", path=").append(path);
        sb.append(", url=").append(url);
        sb.append(", thumbNum=").append(thumbNum);
        sb.append(", collectedNum=").append(collectedNum);
        sb.append(", picDesc=").append(picDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}