package com.ssm.model;

import java.io.Serializable;

public class Post implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_title
     *
     * @mbggenerated
     */
    private String postTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_authorid
     *
     * @mbggenerated
     */
    private Integer postAuthorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_created_by
     *
     * @mbggenerated
     */
    private String postCreatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_created_at
     *
     * @mbggenerated
     */
    private Integer postCreatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.post_content
     *
     * @mbggenerated
     */
    private String postContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table post
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.pid
     *
     * @return the value of post.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.pid
     *
     * @param pid the value for post.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_title
     *
     * @return the value of post.post_title
     *
     * @mbggenerated
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_title
     *
     * @param postTitle the value for post.post_title
     *
     * @mbggenerated
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_authorid
     *
     * @return the value of post.post_authorid
     *
     * @mbggenerated
     */
    public Integer getPostAuthorid() {
        return postAuthorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_authorid
     *
     * @param postAuthorid the value for post.post_authorid
     *
     * @mbggenerated
     */
    public void setPostAuthorid(Integer postAuthorid) {
        this.postAuthorid = postAuthorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_created_by
     *
     * @return the value of post.post_created_by
     *
     * @mbggenerated
     */
    public String getPostCreatedBy() {
        return postCreatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_created_by
     *
     * @param postCreatedBy the value for post.post_created_by
     *
     * @mbggenerated
     */
    public void setPostCreatedBy(String postCreatedBy) {
        this.postCreatedBy = postCreatedBy == null ? null : postCreatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_created_at
     *
     * @return the value of post.post_created_at
     *
     * @mbggenerated
     */
    public Integer getPostCreatedAt() {
        return postCreatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_created_at
     *
     * @param postCreatedAt the value for post.post_created_at
     *
     * @mbggenerated
     */
    public void setPostCreatedAt(Integer postCreatedAt) {
        this.postCreatedAt = postCreatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.post_content
     *
     * @return the value of post.post_content
     *
     * @mbggenerated
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.post_content
     *
     * @param postContent the value for post.post_content
     *
     * @mbggenerated
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent == null ? null : postContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Post other = (Post) that;
        return (this.getPid() == null ? other.getPid() == null : this.getPid().equals(other.getPid()))
            && (this.getPostTitle() == null ? other.getPostTitle() == null : this.getPostTitle().equals(other.getPostTitle()))
            && (this.getPostAuthorid() == null ? other.getPostAuthorid() == null : this.getPostAuthorid().equals(other.getPostAuthorid()))
            && (this.getPostCreatedBy() == null ? other.getPostCreatedBy() == null : this.getPostCreatedBy().equals(other.getPostCreatedBy()))
            && (this.getPostCreatedAt() == null ? other.getPostCreatedAt() == null : this.getPostCreatedAt().equals(other.getPostCreatedAt()))
            && (this.getPostContent() == null ? other.getPostContent() == null : this.getPostContent().equals(other.getPostContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPid() == null) ? 0 : getPid().hashCode());
        result = prime * result + ((getPostTitle() == null) ? 0 : getPostTitle().hashCode());
        result = prime * result + ((getPostAuthorid() == null) ? 0 : getPostAuthorid().hashCode());
        result = prime * result + ((getPostCreatedBy() == null) ? 0 : getPostCreatedBy().hashCode());
        result = prime * result + ((getPostCreatedAt() == null) ? 0 : getPostCreatedAt().hashCode());
        result = prime * result + ((getPostContent() == null) ? 0 : getPostContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", postTitle=").append(postTitle);
        sb.append(", postAuthorid=").append(postAuthorid);
        sb.append(", postCreatedBy=").append(postCreatedBy);
        sb.append(", postCreatedAt=").append(postCreatedAt);
        sb.append(", postContent=").append(postContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}