package com.ssm.model;

import java.io.Serializable;

public class Reply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rid
     *
     * @mbggenerated
     */
    private Long rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.authorid
     *
     * @mbggenerated
     */
    private Long authorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_to_cid
     *
     * @mbggenerated
     */
    private Long replyToCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_at
     *
     * @mbggenerated
     */
    private Long replyAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rid
     *
     * @return the value of reply.rid
     *
     * @mbggenerated
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rid
     *
     * @param rid the value for reply.rid
     *
     * @mbggenerated
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.authorid
     *
     * @return the value of reply.authorid
     *
     * @mbggenerated
     */
    public Long getAuthorid() {
        return authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.authorid
     *
     * @param authorid the value for reply.authorid
     *
     * @mbggenerated
     */
    public void setAuthorid(Long authorid) {
        this.authorid = authorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_to_cid
     *
     * @return the value of reply.reply_to_cid
     *
     * @mbggenerated
     */
    public Long getReplyToCid() {
        return replyToCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_to_cid
     *
     * @param replyToCid the value for reply.reply_to_cid
     *
     * @mbggenerated
     */
    public void setReplyToCid(Long replyToCid) {
        this.replyToCid = replyToCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_at
     *
     * @return the value of reply.reply_at
     *
     * @mbggenerated
     */
    public Long getReplyAt() {
        return replyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_at
     *
     * @param replyAt the value for reply.reply_at
     *
     * @mbggenerated
     */
    public void setReplyAt(Long replyAt) {
        this.replyAt = replyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.content
     *
     * @return the value of reply.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.content
     *
     * @param content the value for reply.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Reply other = (Reply) that;
        return (this.getRid() == null ? other.getRid() == null : this.getRid().equals(other.getRid()))
            && (this.getAuthorid() == null ? other.getAuthorid() == null : this.getAuthorid().equals(other.getAuthorid()))
            && (this.getReplyToCid() == null ? other.getReplyToCid() == null : this.getReplyToCid().equals(other.getReplyToCid()))
            && (this.getReplyAt() == null ? other.getReplyAt() == null : this.getReplyAt().equals(other.getReplyAt()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRid() == null) ? 0 : getRid().hashCode());
        result = prime * result + ((getAuthorid() == null) ? 0 : getAuthorid().hashCode());
        result = prime * result + ((getReplyToCid() == null) ? 0 : getReplyToCid().hashCode());
        result = prime * result + ((getReplyAt() == null) ? 0 : getReplyAt().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", authorid=").append(authorid);
        sb.append(", replyToCid=").append(replyToCid);
        sb.append(", replyAt=").append(replyAt);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}