package com.ssm.model;

import java.io.Serializable;

public class Reply implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.rid
     *
     * @mbggenerated
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_authorid
     *
     * @mbggenerated
     */
    private Integer replyAuthorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_to_cid
     *
     * @mbggenerated
     */
    private Integer replyToCid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_at
     *
     * @mbggenerated
     */
    private Integer replyAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.reply_content
     *
     * @mbggenerated
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.rid
     *
     * @return the value of reply.rid
     *
     * @mbggenerated
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.rid
     *
     * @param rid the value for reply.rid
     *
     * @mbggenerated
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_authorid
     *
     * @return the value of reply.reply_authorid
     *
     * @mbggenerated
     */
    public Integer getReplyAuthorid() {
        return replyAuthorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_authorid
     *
     * @param replyAuthorid the value for reply.reply_authorid
     *
     * @mbggenerated
     */
    public void setReplyAuthorid(Integer replyAuthorid) {
        this.replyAuthorid = replyAuthorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_to_cid
     *
     * @return the value of reply.reply_to_cid
     *
     * @mbggenerated
     */
    public Integer getReplyToCid() {
        return replyToCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_to_cid
     *
     * @param replyToCid the value for reply.reply_to_cid
     *
     * @mbggenerated
     */
    public void setReplyToCid(Integer replyToCid) {
        this.replyToCid = replyToCid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_at
     *
     * @return the value of reply.reply_at
     *
     * @mbggenerated
     */
    public Integer getReplyAt() {
        return replyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_at
     *
     * @param replyAt the value for reply.reply_at
     *
     * @mbggenerated
     */
    public void setReplyAt(Integer replyAt) {
        this.replyAt = replyAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.reply_content
     *
     * @return the value of reply.reply_content
     *
     * @mbggenerated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.reply_content
     *
     * @param replyContent the value for reply.reply_content
     *
     * @mbggenerated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Reply other = (Reply) that;
        return (this.getRid() == null ? other.getRid() == null : this.getRid().equals(other.getRid()))
            && (this.getReplyAuthorid() == null ? other.getReplyAuthorid() == null : this.getReplyAuthorid().equals(other.getReplyAuthorid()))
            && (this.getReplyToCid() == null ? other.getReplyToCid() == null : this.getReplyToCid().equals(other.getReplyToCid()))
            && (this.getReplyAt() == null ? other.getReplyAt() == null : this.getReplyAt().equals(other.getReplyAt()))
            && (this.getReplyContent() == null ? other.getReplyContent() == null : this.getReplyContent().equals(other.getReplyContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRid() == null) ? 0 : getRid().hashCode());
        result = prime * result + ((getReplyAuthorid() == null) ? 0 : getReplyAuthorid().hashCode());
        result = prime * result + ((getReplyToCid() == null) ? 0 : getReplyToCid().hashCode());
        result = prime * result + ((getReplyAt() == null) ? 0 : getReplyAt().hashCode());
        result = prime * result + ((getReplyContent() == null) ? 0 : getReplyContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", replyAuthorid=").append(replyAuthorid);
        sb.append(", replyToCid=").append(replyToCid);
        sb.append(", replyAt=").append(replyAt);
        sb.append(", replyContent=").append(replyContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}