package com.ssm.model;

import java.io.Serializable;

public class UserAlbum implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_album.user_album_id
     *
     * @mbggenerated
     */
    private Long userAlbumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_album.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_album.album_id
     *
     * @mbggenerated
     */
    private Long albumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_album
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_album.user_album_id
     *
     * @return the value of user_album.user_album_id
     *
     * @mbggenerated
     */
    public Long getUserAlbumId() {
        return userAlbumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_album.user_album_id
     *
     * @param userAlbumId the value for user_album.user_album_id
     *
     * @mbggenerated
     */
    public void setUserAlbumId(Long userAlbumId) {
        this.userAlbumId = userAlbumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_album.user_id
     *
     * @return the value of user_album.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_album.user_id
     *
     * @param userId the value for user_album.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_album.album_id
     *
     * @return the value of user_album.album_id
     *
     * @mbggenerated
     */
    public Long getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_album.album_id
     *
     * @param albumId the value for user_album.album_id
     *
     * @mbggenerated
     */
    public void setAlbumId(Long albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserAlbum other = (UserAlbum) that;
        return (this.getUserAlbumId() == null ? other.getUserAlbumId() == null : this.getUserAlbumId().equals(other.getUserAlbumId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAlbumId() == null ? other.getAlbumId() == null : this.getAlbumId().equals(other.getAlbumId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserAlbumId() == null) ? 0 : getUserAlbumId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAlbumId() == null) ? 0 : getAlbumId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_album
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userAlbumId=").append(userAlbumId);
        sb.append(", userId=").append(userId);
        sb.append(", albumId=").append(albumId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}